name: CI

on: [push]

jobs:
  test:
    name: Swift Connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Print Swift Version
        uses: ./
        with:
          auth_check: false
          args: --version

      - name: Test File Listing
        uses: ./
        env:
          OS_AUTH_URL: ${{ secrets.AUTH_URL }}
          OS_PASSWORD: ${{ secrets.PASSWORD }}
          OS_PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.REGION_NAME }}
          OS_USERNAME: ${{ secrets.USERNAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.USER_DOMAIN_NAME }}
        with:
          args: list openstack-swift-action
