name: CI

on: [push]

jobs:
  test:
    name: Swift Connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Print Swift Version
        uses: ./
        with:
          auth-check: false
          args: --version
      - name: Test File Listing
        uses: ./
        env:
          OS_AUTH_URL: ${{ secrets.AUTH_URL }}
          OS_REGION_NAME: ${{ secrets.REGION }}
          OS_TENANT_ID: ${{ secrets.TENANT_ID }}
          OS_USERNAME: ${{ secrets.USERNAME }}
          OS_PASSWORD: ${{ secrets.PASSWORD }}
        with:
          args: list openstack-swift-action