name: CI

on: [push]

jobs:
  test:
    name: Test Swift Connection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        env:
          OS_AUTH_URL: ${{ secrets.AUTH_URL }}
          OS_REGION_NAME: ${{ secrets.REGION }}
          OS_TENANT_ID: ${{ secrets.TENANT_ID }}
          OS_USERNAME: ${{ secrets.USERNAME }}
          OS_PASSWORD: ${{ secrets.PASSWORD }}
        args: swift list openstack-swift-action